dataRegion=["FS_Northern_Region", "FS_Rocky_Mountain_Region", "FS_Southwestern_Region", "FS_Intermountain_Region",
 "FS_Pacific_Southwest_Region","FS_Pacific_Northwest_Region","FS_Southern_Region","FS_Eastern_Region","FS_Alaska_Region",
 "NPS_AKR","NPS_IMR","NPS_MWR","NPS_NCR","NPS_NER","NPS_PWR","NPS_SER","BLM_Alaska","BLM_Arizona","BLM_California","BLM_Colorado",
 "BLM_Eastern_States","BLM_Idaho","BLM_Montana/Dakotas","BLM_Nevada","BLM_New_Mexico","BLM_Oregon/Washington","BLM_Utah","BLM_Wyoming"]; 
dataLocal=["FS_Northern_Region_Beaverhead-Deerlodge_National_Forest","FS_Northern_Region_Bitterroot_National_Forest",
"FS_Northern_Region_Dakota_Prairie_National_Grasslands","FS_Northern_Region_Flathead_National_Forest","FS_Northern_Region_Custer_Gallatin_National_Forest",
"FS_Northern_Region_Helena_National_Forest","FS_Northern_Region_Idaho_Panhandle_National_Forests","FS_Northern_Region_Kootenai_National_Forest",
"FS_Northern_Region_Lewis_&_Clark_National_Forest","FS_Northern_Region_Lolo_National_Forest","FS_Northern_Region_Nez_Perce-Clearwater_National_Forests",
"FS_Rocky_Mountain_Region_Arapaho_and_Roosevelt_National_Forests_and_Pawnee_National_Grassland","FS_Rocky_Mountain_Region_Bighorn_National_Forest",
"FS_Rocky_Mountain_Region_Black_Hills_National_Forest","FS_Rocky_Mountain_Region_Grand_Mesa,Uncompahgre_and_Gunnison_National_Forests",
"FS_Rocky_Mountain_Region_Medicine_Bow-Routt_National_Forests_and_Thunder_Basin_National_Grassland","FS_Rocky_Mountain_Region_Nebraska_ National_Forests_and_Grasslands",
"FS_Rocky_Mountain_Region_Pike_and_San_Isabel_National_Forests_Cimarron_and_Comanche_National_Grasslands","FS_Rocky_Mountain_Region_Rio_Grande_National_Forest",
"FS_Rocky_Mountain_Region_San_Juan_National_Forest","FS_Rocky_Mountain_Region_Shoshone_National_Forest","FS_Rocky_Mountain_Region_White_River_National_Forest",
"FS_Southwestern_Region_Apache-Sitgreaves_National_Forests","FS_Southwestern_Region_Carson_National_Forest","FS_Southwestern_Region_Cibola_National_Forest",
"FS_Southwestern_Region_Coconino_National_Forest","FS_Southwestern_Region_Coronado_National_Forest","FS_Southwestern_Region_Gila_National_Forest",
"FS_Southwestern_Region_Kaibab_National_Forest","FS_Southwestern_Region_Lincoln_National_Forest","FS_Southwestern_Region_Prescott_National_Forest",
"FS_Southwestern_Region_Santa_Fe_National_Forest","FS_Southwestern_Region_Tonto_National_Forest",
"FS_Intermountain_Region_Ashley_National_Forest","FS_Intermountain_Region_Boise_National_Forest","FS_Intermountain_Region_Bridger-Teton_National_Forest",
"FS_Intermountain_Region_Caribou-Targhee_National_Forest","FS_Intermountain_Region_Dixie_National_Forest","FS_Intermountain_Region_Fishlake_National_Forest",
"FS_Intermountain_Region_Humboldt-Toiyabe_National_Forest","FS_Intermountain_Region_Manti-LaSal_National_Forest","FS_Intermountain_Region_Payette_National_Forest",
"FS_Intermountain_Region_Salmon-Challis_National_Forest","FS_Intermountain_Region_Sawtooth_National_Forest","FS_Intermountain_Region_Uinta-Wasatch-Cache_National_Forest",
"FS_Pacific_Southwest_Region_Angeles_National_Forest","FS_Pacific_Southwest_Region_Cleveland_National_Forest","FS_Pacific_Southwest_Region_Eldorado_National_Forest",
"FS_Pacific_Southwest_Region_Inyo_National_Forest","FS_Pacific_Southwest_Region_Klamath_National_Forest","FS_Pacific_Southwest_Region_Lake_Tahoe_Basin_Management_Unit",
"FS_Pacific_Southwest_Region_Lassen_National_Forest","FS_Pacific_Southwest_Region_Los_Padres_National_Forest","FS_Pacific_Southwest_Region_Mendocino_National_Forest",
"FS_Pacific_Southwest_Region_Modoc_National_Forest","FS_Pacific_Southwest_Region_Plumas_National_Forest","FS_Pacific_Southwest_Region_San_Bernardino_National_Forest",
"FS_Pacific_Southwest_Region_Sequoia_National_Forest","FS_Pacific_Southwest_Region_Shasta-Trinity_National_Forest","FS_Pacific_Southwest_Region_Sierra_National_Forest",
"FS_Pacific_Southwest_Region_Six_Rivers_National_Forest","FS_Pacific_Southwest_Region_Stanislaus_National_Forest","FS_Pacific_Southwest_Region_Tahoe_National_Forest",
"FS_Pacific_Northwest_Region_Columbia_River_Gorge_National_Scenic_Area","FS_Pacific_Northwest_Region_Colville_National_Forest",
"FS_Pacific_Northwest_Region_Crooked_River_National_Grassland","FS_Pacific_Northwest_Region_Deschutes_National_Forest",
"FS_Pacific_Northwest_Region_Fremont-Winema_National_Forest","FS_Pacific_Northwest_Region_Gifford_Pinchot_National_Forest",
"FS_Pacific_Northwest_Region_Malheur_National_Forest","FS_Pacific_Northwest_Region_Mt._Baker-Snoqualmie_National_Forest",
"FS_Pacific_Northwest_Region_Mt._Hood_National_Forest","FS_Pacific_Northwest_Region_Ochoco_National_Forest","FS_Pacific_Northwest_Region_Okanogan-Wenatchee_National_Forest",
"FS_Pacific_Northwest_Region_Olympic_National_Forest","FS_Pacific_Northwest_Region_Siuslaw_National_Forest","FS_Pacific_Northwest_Region_Rogue_River-Siskiyou_National_Forest",
"FS_Pacific_Northwest_Region_Umatilla_National_Forest","FS_Pacific_Northwest_Region_Umpqua_National_Forest",
"FS_Pacific_Northwest_Region_Wallowa-Whitma_National_Forest","FS_Pacific_Northwest_Region_Willamette_National_Forest",
"FS_Southern_Region_Chattahoochee-Oconee_National_Forest","FS_Southern_Region_Cherokee_National_Forest","FS_Southern_Region_Daniel_Boone_National_Forest",
"FS_Southern_Region_El_Yunque_National_Forest","FS_Southern_Region_Francis_Marion_and_Sumter_National_Forests",
"FS_Southern_Region_George_Washington_and_Jefferson_National_Forests","FS_Southern_Region_Kisatchie_National_Forest",
"FS_Southern_Region_Land_Between_the_Lakes_Recreation_Area","FS_Southern_Region_National_Forests_and_Grasslands_in_Texas",
"FS_Southern_Region_National_Forests_in_Alabama","FS_Southern_Region_National_Forests_in_Florida","FS_Southern_Region_National_Forests_in_Mississippi",
"FS_Southern_Region_National_Forests_in_North_Carolina","FS_Southern_Region_Ouachita_National_Forest",
"FS_Southern_Region_Ozark-St._Francis_National_Forest","FS_Southern_Region_Savannah_River_Site",
"FS_Eastern_Region_Allegheny_National_Forest","FS_Eastern_Region_Chequamegon-Nicolet_National_Forest","FS_Eastern_Region_Chippewa_National_Forest",
"FS_Eastern_Region_Green_Mountain_&_Finger_Lakes_National_Forests","FS_Eastern_Region_Hiawatha_National_Forest","FS_Eastern_Region_Hoosier_National_Forest",
"FS_Eastern_Region_Huron-Manistee_National_Forests","FS_Eastern_Region_Mark_Twain_National_Forest","FS_Eastern_Region_Midewin_National_Tallgrass_Prairie",
"FS_Eastern_Region_Monongahela_National_Forest","FS_Eastern_Region_Ottawa_National_Forest","FS_Eastern_Region_Shawnee_National_Forest",
"FS_Eastern_Region_Superior_National_Forest","FS_Eastern_Region_Wayne_National_Forest","FS_Eastern_Region_White_Mountain_National_Forest",
"FS_Alaska_Region_Chugach_National_Forest","FS_Alaska_Region_Tongass_National_Forest",
"NPS_AKR_KLONDIKE_GOLD_RUSH","NPS_AKR_SITKA","NPS_AKR_CAPE_KRUSENSTERN","NPS_AKR_ANIAKCHAK","NPS_AKR_KENAI_FJORDS",
"NPS_AKR_KOBUK_VALLEY","NPS_AKR_DENALI","NPS_AKR_GATES_OF_THE_ARCTIC","NPS_AKR_GLACIER_BAY","NPS_AKR_KATMAI",
"NPS_AKR_LAKE_CLARK","NPS_AKR_WRANGELL-ST._ELIAS","NPS_AKR_BERING_LAND_BRIDGE","NPS_AKR_NOATAK",
"NPS_AKR_YUKON-CHARLEY_RIVERS","NPS_IMR_JOHN_D._ROCKEFELLER,_JR.,","NPS_IMR_CHACO_CULTURE","NPS_IMR_LYNDON_B._JOHNSON",
"NPS_IMR_MANHATTAN_PROJECT","NPS_IMR_PALO_ALTO","NPS_IMR_PECOS","NPS_IMR_SAN_ANTONIO_MISSIONS","NPS_IMR_TUMACACORI",
"NPS_IMR_BENTS_OLD_FORT","NPS_IMR_FORT_BOWIE","NPS_IMR_FORT_DAVIS","NPS_IMR_FORT_LARAMIE","NPS_IMR_GOLDEN_SPIKE",
"NPS_IMR_GRANT-KOHRS_RANCH","NPS_IMR_HUBBELL_TRADING_POST","NPS_IMR_SAND_CREEK_MASSACRE","NPS_IMR_WASHITA",
"NPS_IMR_ALIBATES_FLINT_QUARRIES","NPS_IMR_AZTEC_RUINS","NPS_IMR_BANDELIER","NPS_IMR_CANYON_DE_CHELLY",
"NPS_IMR_CAPULIN_VOLCANO","NPS_IMR_CASA_GRANDE_RUINS","NPS_IMR_CEDAR_BREAKS","NPS_IMR_CHIRICAHUA","NPS_IMR_COLORADO",
"NPS_IMR_DEVILS_TOWER","NPS_IMR_DINOSAUR","NPS_IMR_EL_MALPAIS","NPS_IMR_EL_MORRO","NPS_IMR_FLORISSANT_FOSSIL_BEDS",
"NPS_IMR_FORT_UNION","NPS_IMR_FOSSIL_BUTTE","NPS_IMR_GILA_CLIFF_DWELLINGS","NPS_IMR_HOHOKAM_PIMA","NPS_IMR_HOVENWEEP",
"NPS_IMR_LITTLE_BIGHORN","NPS_IMR_MONTEZUMA_CASTLE","NPS_IMR_NATURAL_BRIDGES","NPS_IMR_NAVAJO","NPS_IMR_ORGAN_PIPE_CACTUS",
"NPS_IMR_PETROGLYPH","NPS_IMR_PIPE_SPRING","NPS_IMR_RAINBOW_BRIDGE","NPS_IMR_SALINAS_PUEBLO_MISSIONS",
"NPS_IMR_SUNSET_CRATER_VOLCANO","NPS_IMR_TIMPANOGOS_CAVE","NPS_IMR_TONTO","NPS_IMR_TUZIGOOT","NPS_IMR_WACO_MAMMOTH",
"NPS_IMR_WALNUT_CANYON","NPS_IMR_WHITE_SANDS","NPS_IMR_WUPATKI","NPS_IMR_YUCCA_HOUSE","NPS_IMR_CHAMIZAL",
"NPS_IMR_CORONADO","NPS_IMR_ARCHES","NPS_IMR_BIG_BEND","NPS_IMR_BLACK_CANYON_OF_THE_GUNNISON","NPS_IMR_BRYCE_CANYON",
"NPS_IMR_CANYONLANDS","NPS_IMR_CAPITOL_REEF","NPS_IMR_CARLSBAD_CAVERNS","NPS_IMR_GLACIER","NPS_IMR_GRAND_CANYON",
"NPS_IMR_GRAND_TETON","NPS_IMR_GUADALUPE_MOUNTAINS","NPS_IMR_MESA_VERDE","NPS_IMR_PETRIFIED_FOREST",
"NPS_IMR_ROCKY_MOUNTAIN","NPS_IMR_SAGUARO","NPS_IMR_YELLOWSTONE","NPS_IMR_ZION","NPS_IMR_BIG_THICKET",
"NPS_IMR_GREAT_SAND_DUNES","NPS_IMR_VALLES_CALDERA","NPS_IMR_AMISTAD","NPS_IMR_BIGHORN_CANYON ","NPS_IMR_CHICKASAW",
"NPS_IMR_CURECANTI","NPS_IMR_GLEN_CANYON","NPS_IMR_LAKE_MEREDITH","NPS_IMR_PADRE_ISLAND","NPS_IMR_RIO_GRANDE",
"NPS_MWR_JEFFERSON_NATIONAL_EXPANSION","NPS_MWR_WILSON’S_CREEK","NPS_MWR_RIVER_RAISIN","NPS_MWR_DAYTON_AVIATION_HERITAGE",
"NPS_MWR_GEORGE_ROGERS_CLARK","NPS_MWR_HOPEWELL_CULTURE","NPS_MWR_KEWEENAW","NPS_MWR_BROWN_V._BOARD_OF_EDUCATION",
"NPS_MWR_FIRST_LADIES'","NPS_MWR_FORT_LARNED","NPS_MWR_FORT_SCOTT","NPS_MWR_FORT_SMITH","NPS_MWR_FORT_UNION_TRADING_POST",
"NPS_MWR_HARRY_S_TRUMAN","NPS_MWR_HERBERT_HOOVER","NPS_MWR_JAMES_A._GARFIELD","NPS_MWR_KNIFE_RIVER_INDIAN_VILLAGES",
"NPS_MWR_LINCOLN_HOME","NPS_MWR_LITTLE_ROCK_CENTRAL_HIGH_SCHOOL","NPS_MWR_MINUTEMAN_MISSILE","NPS_MWR_NICODEMUS",
"NPS_MWR_PRESIDENT_WILLIAM_JEFFERSON_CLINTON_BIRTHPLACE_HOME","NPS_MWR_ULYSSES_S._GRANT","NPS_MWR_WILLIAM_HOWARD_TAFT",
"NPS_MWR_APOSTLE_ISLANDS","NPS_MWR_INDIANA_DUNES","NPS_MWR_PICTURED_ROCKS","NPS_MWR_SLEEPING_BEAR_DUNES",
"NPS_MWR_AGATE_FOSSIL_BEDS","NPS_MWR_CHARLES_YOUNG_BUFFALO_SOLDIERS","NPS_MWR_EFFIGY_MOUNDS",
"NPS_MWR_GEORGE_WASHINGTON_CARVER","NPS_MWR_GRAND_PORTAGE","NPS_MWR_HOMESTEAD","NPS_MWR_JEWEL_CAVE","NPS_MWR_PIPESTONE",
"NPS_MWR_PULLMAN","NPS_MWR_SCOTTS_BLUFF","NPS_MWR_ARKANSAS_POST","NPS_MWR_LINCOLN_BOYHOOD","NPS_MWR_MOUNT_RUSHMORE",
"NPS_MWR_PERRY’S_VICTORY_AND_INTERNATIONAL_PEACE_MEMORIAL","NPS_MWR_PEA_RIDGE","NPS_MWR_BADLANDS",
"NPS_MWR_CUYAHOGA_VALLEY","NPS_MWR_HOT_SPRINGS","NPS_MWR_ISLE_ROYALE","NPS_MWR_THEODORE_ROOSEVELT","NPS_MWR_VOYAGEURS",
"NPS_MWR_WIND_CAVE","NPS_MWR_TALLGRASS_PRAIRIE","NPS_MWR_BUFFALO","NPS_MWR_MISSISSIPPI_NATIONAL_RIVER_AND_RECREATION_AREA",
"NPS_MWR_NIOBRARA","NPS_MWR_OZARK_NATIONAL_SCENIC_RIVERWAY","NPS_MWR_SAINT_CROIX","NPS_MWR_MISSOURI_NATIONAL_RECREATIONAL_RIVER",
"NPS_NCR_LINCOLN","NPS_NCR_THOMAS_JEFFERSON","NPS_NCR_VIETNAM_VETERANS","NPS_NCR_WORLD_WAR_II",
"NPS_NCR_GEORGE_WASHINGTON_MEMORIAL_PARKWAY","NPS_NCR_ANTIETAM","NPS_NCR_MONOCACY","NPS_NCR_MANASSAS",
"NPS_NCR_CHESAPEAKE_AND_OHIO_CANAL","NPS_NCR_HARPERS_FERRY","NPS_NCR_CARTER_G._WOODSON_HOME","NPS_NCR_CLARA_BARTON",
"NPS_NCR_FORD'S_THEATRE","NPS_NCR_FREDERICK_DOUGLASS","NPS_NCR_MARY_MCLEOD_BETHUNE_COUNCIL_HOUSE",
"NPS_NCR_PENNSYLVANIA_AVENUE","NPS_NCR_BELMONT-PAUL_WOMEN'S_EQUALITY","NPS_NCR_ARLINGTON_HOUSE_-_ROBERT_E._LEE_MEMORIAL",
"NPS_NCR_FRANKLIN_DELANO_ROOSEVELT","NPS_NCR_KOREAN_WAR_VETERANS",
"NPS_NCR_LYNDON_BAINES_JOHNSON_MEMORIAL_GROVE_ON_THE_POTOMAC","NPS_NCR_MARTIN_LUTHER_KING,_JR.",
"NPS_NCR_THEODORE_ROOSEVELT_ISLAND","NPS_NCR_WORLD_WAR_I","NPS_NCR_POTOMAC_HERITAGE","NPS_NCR_CONSTITUTION_GARDENS",
"NPS_NCR_NATIONAL_CAPITAL_PARKS_-_EAST","NPS_NCR_NATIONAL_MALL","NPS_NCR_PRINCE_WILLIAM_FOREST_PARK",
"NPS_NCR_WASHINGTON_MONUMENT","NPS_NCR_WHITE_HOUSE_PRESIDENTS_PARK","NPS_NCR_WOLF_TRAP_PARK_FOR_THE_PERFORMING_ARTS",
"NPS_NCR_CATOCTIN_MOUNTAIN","NPS_NCR_FORT_WASHINGTON","NPS_NCR_GREEN_BELT","NPS_NCR_PISCATAWAY","NPS_NCR_ROCK_CREEK",
"NPS_NER_FORT_NECESSITY","NPS_NER_PETERSBURG","NPS_NER_RICHMOND","NPS_NER_ADAMS","NPS_NER_APPOMATTOX_COURT_HOUSE",
"NPS_NER_BLACKSTONE_RIVER_VALLEY","NPS_NER_BOSTON","NPS_NER_CEDAR_CREEK_&_BELLE_GROVE","NPS_NER_COLONIAL",
"NPS_NER_FIRST_STATE","NPS_NER_HARRIET_TUBMAN_UNDERGROUND_RAILROAD","NPS_NER_INDEPENDENCE","NPS_NER_LOWELL",
"NPS_NER_MARSH-BILLINGS-ROCKEFELLER","NPS_NER_MINUTE_MAN","NPS_NER_MORRISTOWN","NPS_NER_NEW_BEDFORD_WHALING",
"NPS_NER_PATERSON_GREAT_FALLS","NPS_NER_SARATOGA","NPS_NER_THOMAS_EDISON","NPS_NER_VALLEY_FORGE","NPS_NER_WOMEN'S_RIGHTS",
"NPS_NER_ALLEGHENY_PORTAGE_RAILROAD","NPS_NER_BOSTON_AFRICAN_AMERICAN","NPS_NER_EDGAR_ALLAN_POE","NPS_NER_EISENHOWER",
"NPS_NER_ELEANOR_ROOSEVELT","NPS_NER_FREDRICK_LAW_OLMSTED","NPS_NER_FRIENDSHIP_HILL","NPS_NER_HAMPTON",
"NPS_NER_HOME_OF_FRANKLIN_D._ROOSEVELT","NPS_NER_HOPEWELL_FURNACE","NPS_NER_JOHN_FITZGERALD_KENNEDY",
"NPS_NER_LONGFELLOW_HOUSE_-WASHINGTON'S_HEADQUARTERS","NPS_NER_MAGGIE_L._WALKER","NPS_NER_MARTIN_VAN_BUREN",
"NPS_NER_SAGAMORE_HILL","NPS_NER_SAINT_PAUL'S_CHURCH","NPS_NER_SAINT-GAUDENS","NPS_NER_SALEM_MARITIME",
"NPS_NER_SAUGUS_IRON_WORKS","NPS_NER_SPRINGFIELD_ARMORY","NPS_NER_STEAMTOWN","NPS_NER_THEODORE_ROOSEVELT_BIRTHPLACE",
"NPS_NER_THOMAS_STONE","NPS_NER_VANDERBILT_MANSION","NPS_NER_WEIR_FARM","NPS_NER_AFRICAN_BURIAL_GROUND",
"NPS_NER_BOOKER_T._WASHINGTON_NM","NPS_NER_CASTLE_CLINTON","NPS_NER_FORT_MONROE","NPS_NER_FORT_STANWIX",
"NPS_NER_GEORGE_WASHINGTON_BIRTHPLACE","NPS_NER_GOVERNORS_ISLAND","NPS_NER_KATAHDIN_WOODS_AND_WATERS",
"NPS_NER_STATUE_OF_LIBERTY_AND_ELLIS_ISLAND","NPS_NER_STONEWALL","NPS_NER_FEDERAL_HALL","NPS_NER_FLIGHT_93",
"NPS_NER_GENERAL_GRANT","NPS_NER_HAMILTON_GRANGE_NM","NPS_NER_JOHNSTOWN_FLOOD_NM","NPS_NER_ROGER_WILLIAMS",
"NPS_NER_THADDEUS_KOSCIUSZKO","NPS_NER_FREDRICKSBURG_&_SPOTSYLVANIA","NPS_NER_GETTYSBURG","NPS_NER_ACADIA",
"NPS_NER_SHENANDOAH","NPS_NER_NEW_RIVER_GORGE","NPS_NER_BOSTON_HARBOR_ISLANDS","NPS_NER_DELAWARE_WATER_GAP",
"NPS_NER_GATEWAY","NPS_NER_GAULEY","NPS_NER_ASSATEAGUE_ISLAND_NS","NPS_NER_CAPE_COD","NPS_NER_FIRE_ISLAND",
"NPS_NER_BLUESTONE","NPS_NER_FORT_MCHENRY_NATIONAL_MONUMENT_AND_HISTORIC_SHRINE",
"NPS_NER_SAINT_CROIX_ISLAND_INTERNATIONAL_HISTORIC_SITE","NPS_NER_GREAT_EGG_HARBOR","NPS_NER_UPPER_DELAWARE",
"NPS_NER_APPALACHIAN","NPS_PWR_BIG_HOLE","NPS_PWR_KALAUPAPA","NPS_PWR_KALOKO-HONOKOHAU","NPS_PWR_KLONDIKE_GOLD_RUSH",
"NPS_PWR_LEWIS_AND_CLARK","NPS_PWR_NEZ_PERCE","NPS_PWR_PU'UHONUA_O_HONAUNAU","NPS_PWR_ROSIE_THE_RIVETER/WWII_HOME_FRONT",
"NPS_PWR_SAN_FRANCISCO_MARITIME","NPS_PWR_WAR_IN_THE_PACIFIC","NPS_PWR_EUGENE_O'NEILL","NPS_PWR_FORT_POINT",
"NPS_PWR_FORT_VANCOUVER","NPS_PWR_JOHN_MUIR","NPS_PWR_MANZANAR","NPS_PWR_MINIDOKA","NPS_PWR_PU'UKOHOLA_HEIAU",
"NPS_PWR_SAN_JUAN_ISLAND","NPS_PWR_WHITMAN_MISSION","NPS_PWR_CABRILLO","NPS_PWR_CASTLE_MOUNTAIN",
"NPS_PWR_CESAR_E._CHAVEZ","NPS_PWR_DEVILS_POSTPILE","NPS_PWR_HAGERMAN_FOSSIL_BEDS","NPS_PWR_HONOULIULI",
"NPS_PWR_JOHN_DAY_FOSSIL_BEDS","NPS_PWR_LAVA_BEDS","NPS_PWR_MUIR_WOODS","NPS_PWR_PORT_CHICAGO_NAVAL_MAGAZINE",
"NPS_PWR_TULE_SPRINGS_FOSSIL_BEDS","NPS_PWR_WORLD_WAR_II_VALOR_IN_THE_PACIFIC","NPS_PWR_OREGON_CAVES",
"NPS_PWR_CRATERS_OF_THE_MOON","NPS_PWR_CHANNEL_ISLANDS","NPS_PWR_CRATER_LAKE","NPS_PWR_DEATH_VALLEY",
"NPS_PWR_GREAT_BASIN","NPS_PWR_HALEAKALA","NPS_PWR_HAWAII_VOLCANOES","NPS_PWR_JOSHUA_TREE","NPS_PWR_KINGS_CANYON",
"NPS_PWR_LASSEN_VOLCANIC","NPS_PWR_MOUNT_RAINIER","NPS_PWR_NATIONAL_PARK_OF_AMERICAN_SAMOA","NPS_PWR_NORTH_CASCADES",
"NPS_PWR_OLYMPIC","NPS_PWR_PINNACLES","NPS_PWR_REDWOOD","NPS_PWR_SEQUOIA","NPS_PWR_YOSEMITE","NPS_PWR_MOJAVE",
"NPS_PWR_GOLDEN_GATE","NPS_PWR_LAKE_CHELAN","NPS_PWR_LAKE_MEAD","NPS_PWR_LAKE_ROOSEVELT","NPS_PWR_ROSS_LAKE",
"NPS_PWR_SANTA_MONICA_MOUNTAINS","NPS_PWR_WHISKEYTOWN","NPS_PWR_POINT_REYES","NPS_PWR_AMERICAN_MEMORIAL_PARK",
"NPS_PWR_CITY_OF_ROCKS_NATIONAL_RESERVE","NPS_PWR_EBEY'S_LANDING_NATIONAL_HISTORICAL_RESERVE","NPS_SER_COWPENS",
"NPS_SER_FORT_DONELSON","NPS_SER_MOORES_CREEK","NPS_SER_STONES_RIVER","NPS_SER_TUPELO","NPS_SER_KENNESAW_MOUNTAIN",
"NPS_SER_ABRAHAM_LINCOLN_BIRTHPLACE","NPS_SER_CUMBERLAND_GAP","NPS_SER_NATCHEZ","NPS_SER_NEW_ORLEANS_JAZZ",
"NPS_SER_ANDERSONVILLE","NPS_SER_ANDREW_JOHNSON","NPS_SER_CARL_SANDBURG_HOME","NPS_SER_CHARLES_PINCKNEY",
"NPS_SER_CHRISTIANSTED","NPS_SER_FORT_RALEIGH","NPS_SER_JIMMY_CARTER","NPS_SER_MARTIN_LUTHER_KING,_JR.",
"NPS_SER_NINETY_SIX","NPS_SER_SAN_JUAN","NPS_SER_TUSKEGEE_AIRMEN","NPS_SER_TUSKEGEE_INSTITUTE","NPS_SER_BUCK_ISLAND_REEF",
"NPS_SER_CASTILLO_de_SAN_MARCOS","NPS_SER_FORT_FREDERICA","NPS_SER_FORT_MATANZAS","NPS_SER_FORT_PULASKI",
"NPS_SER_FORT_SUMTER","NPS_SER_OCMULGEE","NPS_SER_POVERTY_POINT_STATE","NPS_SER_RUSSELL_CAVE",
"NPS_SER_VIRGIN_ISLANDS_CORAL_REEF","NPS_SER_DE_SOTO","NPS_SER_FORT_CAROLINE","NPS_SER_WRIGHT_BROTHERS",
"NPS_SER_CHICKAMAUGA_AND_CHATTANOOGA","NPS_SER_GUILFORD_COURTHOUSE","NPS_SER_HORSESHOE_BEND","NPS_SER_KINGS_MOUNTAIN",
"NPS_SER_SHILOH","NPS_SER_VICKSBURG","NPS_SER_BISCAYNE","NPS_SER_CONGAREE","NPS_SER_DRY_TORTUGAS","NPS_SER_EVERGLADES",
"NPS_SER_GREAT_SMOKY_MOUNTAINS","NPS_SER_MAMMOTH_CAVE","NPS_SER_VIRGIN_ISLANDS","NPS_SER_LITTLE_RIVER_CANYON",
"NPS_SER_BIG_SOUTH_FORK ","NPS_SER_CHATTAHOOCHEE","NPS_SER_CANAVERAL","NPS_SER_CAPE_HATTERAS","NPS_SER_CAPE_LOOKOUT",
"NPS_SER_CUMBERLAND_ISLAND","NPS_SER_GULF_ISLANDS","NPS_SER_APPALACHIAN","NPS_SER_NATCHEZ_TRACE",
"NPS_SER_BRICES_CROSS_ROADS_NATIONAL_BATTLEFIELD_SITE","NPS_SER_CANE_RIVER_CREOLE_NATIONAL_HISTORICAL_PARK_&_HERITAGE_AREA",
"NPS_SER_JEAN_LAFITTE_NATIONAL_HISTORICAL_PARK_&_PRESERVE","NPS_SER_SALT_RIVER_BAY_NATIONAL_HISTORICAL_PARK_&_ECOLOGICAL_PRESERVE",
"NPS_SER_TIMUCUAN_ECOLOGICAL","NPS_SER_BLUE_RIDGE_PARKWAY","NPS_SER_OBED","BLM_Alaska_Fairbanks","BLM_Alaska_Anchorage",
"BLM_Arizona_Arizona_Strip","BLM_Arizona_Colorado_River","BLM_Arizona_Gila","BLM_Arizona_Phoenix","BLM_California_Northern_California",
"BLM_California_Central_California","BLM_California_Desert","BLM_Colorado_Front_Range","BLM_Colorado_Northwest","BLM_Colorado_Southwest",
"BLM_Eastern_States_Jackson_Field_Office","BLM_Eastern_States_Milwaukee_Field_Office","BLM_Idaho_Boise","BLM_Idaho_Coeur_d'Alene",
"BLM_Idaho_Idaho_Falls","BLM_Idaho_Twin_Falls","BLM_Montana/Dakotas_Eastern_Montana/Dakotas","BLM_Montana/Dakotas_North_Central_Montana",
"BLM_Montana/Dakotas_Western_Montana","BLM_Montana/Dakotas_Billings_Field_Office","BLM_Nevada_Battle_Mountain","BLM_Nevada_Carson_City",
"BLM_Nevada_Elko","BLM_Nevada_Ely","BLM_Nevada_Southern_Nevada","BLM_Nevada_Winnemucca","BLM_New_Mexico_Albuquerque",
"BLM_New_Mexico_Farmington","BLM_New_Mexico_Las_Cruces","BLM_New_Mexico_Pecos","BLM_New_Mexico_Amarillo_Field_Office",
"BLM_New_Mexico_Oklahoma_Field_Office","BLM_Oregon/Washington_Burns","BLM_Oregon/Washington_Coos_Bay","BLM_Oregon/Washington_Lakeview",
"BLM_Oregon/Washington_Medford","BLM_Oregon/Washington_Northwest_Oregon","BLM_Oregon/Washington_Prineville",
"BLM_Oregon/Washington_Roseburg","BLM_Oregon/Washington_Spokane","BLM_Oregon/Washington_Vale","BLM_Utah_Canyon_Country",
"BLM_Utah_Color_Country","BLM_Utah_Green_River","BLM_Utah_West_Desert","BLM_Wyoming_Wind_River/Bighorn_Basin",
"BLM_Wyoming_Wyoming_High_Desert","BLM_Wyoming_Wyoming_High_Plains"]; 

dataSide = ["L - For use with roads with mile markers","R - For use with roads with mile markers",
"N - if road direction not specified with mile marker","NE - if road direction not specified with mile marker",
"E - if road direction not specified with mile marker","SE - if road direction not specified with mile marker",
"S - if road direction not specified with mile marker","SW - if road direction not specified with mile marker",
"W - if road direction not specified with mile marker","NW - if road direction not specified with mile marker"];

dataWeather = ['Clear','Clear and Breezy','A Few Clouds','A Few Clouds and Breezy',
'Partly Cloudy','Partly Cloudy and Breezy','Mostly Cloudy','Mostly Cloudy and Breezy',
'Overcast','Overcast and Breezy','Fog','Partial Fog','Freezing Fog','Light Rain','Rain',
'Heavy Rain','Freezing Rain','Thunderstorms','Snow','Smoky/Haze','Unknown'];

dataYesNo=['Yes','No'];

export{dataRegion,dataLocal,dataSide,dataWeather,dataYesNo};